apiVersion: v1
kind: List
items:
  - apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    metadata:
      name: main-pool
      namespace: metallb-system
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      addresses:
        - 192.168.0.20

  # L2Advertisementの設定は変更しない
  - apiVersion: metallb.io/v1beta1
    kind: L2Advertisement
    metadata:
      name: main-l2
      namespace: metallb-system
      annotations:
        argocd.argoproj.io/sync-wave: "1"
