apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/gen-yuu/lab-cluster-app.git"
    targetRevision: HEAD
    path: charts/prometheus # ラッパーチャート
    helm:
      valueFiles:
        - values.yml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
