# apps/prometheus/helm-values.yaml
# 例：Grafanaのダッシュボードにアクセスしやすくするため、Service Typeを変更
---
kube-prometheus-stack:
  # CRDは別のアプリで管理するため、このチャートではインストールしない
  crds:
    enabled: false
  prometheusOperator:
    admissionWebhooks:
      enabled: false
  grafana:
    service:
      type: NodePort
      nodePort: 30000
