---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/gen-yuu/lab-cluster-app.git" # ★ご自身のURL
    targetRevision: HEAD
    path: apps/cicd
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
