---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
  repoURL: "https://github.com/gen-yuu/lab-cluster-app.git"
  targetRevision: HEAD
  path: apps/prometheus
  helm:
    valueFiles:
      - helm-values.yaml
    chart: kube-prometheus-stack
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: "73.2.0" # 2025-06-10
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
